### ISSUE TITLE
TeslaJS error: Error response: 408

### ISSUE THREAD

**Issue by dsully** [mseminatore/TeslaJS#249]
**Describe the bug**
Seeing: `TeslaJS error: Error response: 408` from homebridge-tesla

The auth/login appears to succeed, but any additional API calls get a HTTP 408 (Request Timeout)

**Comment by dsully** [comment]
See also: https://github.com/nfarina/homebridge-tesla/issues/58

**Comment by mseminatore** [comment]
How recently was this happening and are you sure that homebridge-tesla is up to date? I ask because Tesla recently broke things with the Captcha and that took some days to settle back to normal. I used TeslaJS as recently as yesterday and it worked just fine. And the different but similar code in the Tesla Control app is also working as of this morning.

**Comment by dsully** [comment]
It was happening yesterday/today, just after I installed homebridge-tesla which would pull down the most recently published version.

**Comment by mseminatore** [comment]
Please `npm update` and try again. I just discovered I had a one-line change that was not checked in.

**Comment by dsully** [comment]
Unfortunately that didn't do it. It appears when the car is considered "asleep".

**Comment by mseminatore** [comment]
OK, well that is the defined behavior of a sleeping car. If you want to wake up the car, or make sure it is awake there is an API for that. A car that has set `always connected` should not have that problem.
