### ISSUE TITLE
Login returns "credentials rejected"

### ISSUE THREAD

**Issue by mstoyanovv** [mseminatore/TeslaJS#315]
**Describe the bug**
I am trying to login with the example provided in the README but the response is always 'credentials rejected'.
Debugging this futher I can see that the response of the second request that is being made is html with title of "Access Denied". 
Has someone encounter this and fixed it? 

**Steps To Reproduce**
Identify the steps to reproduce the behavior:
1. Download package
2. Create index.js file with the example of login from README
3. Type in username/password and try to log in 

**Expected behavior**
Token retrieved from tesla 

**Library version**
4.10.0

**Comment by mseminatore** [comment]
This is "by design" in that Tesla has broken 3rd party authentication by adding a reCaptcha requirement.

**Comment by edi** [comment]
> This is "by design" in that Tesla has broken 3rd party authentication by adding a reCaptcha requirement. I've considered adding 2captcha support as a way to work-around it but still have some reservations with that plan.

Does this mean that this library is now obsolete? Because not being able to get an auth token, basically means trying to implement this API is pointless no? How do we go about it?

I am working on a service that gives Teslas for rental (pay as you go), and I need to wake the car up when a customer pays for the car. Seems like it is not possible via a CAN adapter, and needs to go through teslas API. Found this in Node, and I'm running into the same "credentials rejected" issue.

Please advise

**Comment by mseminatore** [comment]
The library is not currently functional given the changes that Tesla made to authentication. I would not call it obsolete in the sense that if we are able to find a workaround it will work again. But it can't be used in its current form.

**Comment by edi** [comment]
> The library is not currently functional given the changes that Tesla made to authentication. I would not call it obsolete in the sense that if we are able to find a workaround it will work again. But it can't be used in its current form.

I've made my own solution afterall, via puppeteer (headless chrome tab), since the auth page doesn't seem to like you if there's no javascript support in the page, given they also have an invisible captcha.

I needed it to be purely CLI so .. any manual web-views wouldn't work for me, but, puppeteer (or any other headless browser tool) will work just fine.

I could make a PR, but I guess since this is supposed to be "dependency lean" and puppeteer is not a small dependency, nor will it work with serverless functions, or services like digital ocean's app platform / aws lambda .. I guess my solution is kind of particular and will only work as long as you have your own server.

Let me know anyway.
