### ISSUE TITLE
Error response: 404

### ISSUE THREAD

**Issue by bjm88** [mseminatore/TeslaJS#86]
trying to call certain calls resulting in 404, vehiclesAsync works but other 2 do not..

var tjs = require('TeslaJS');
 
var username = process.env.TSLA_USERNAME;
var password = process.env.TSLA_PASSWORD;
var access_token;

console.log("Attempting to login as " + username)
tjs.login(username, password, function(err, result) {
    if (err) {
      console.log(JSON.stringify(err));
      process.exit(1);
    }
    if (result.error) {
      console.log(JSON.stringify(result.error));
      process.exit(1);
    }
    //console.log("Got results, " + JSON.stringify(result))
    access_token = result.authToken;

    var options = { authToken: access_token };
    console.log("Calling for vehicles ...")

    tjs.vehiclesAsync(options).done(function(vehicle) {
        console.log("Vehicle " + vehicle.vin + " is: " + vehicle.state);
    });

    console.log("Calling for vehicleData ...")
    tjs.vehicleDataAsync(options).done(function (vehicleData) {
            if (err) {
              console.log(JSON.stringify(err));
            }
        console.log("vehicleData: " + JSON.stringify(vehicleData))
    });
    
    console.log("Calling for chargeState ...")
    tjs.chargeStateAsync(options).done(function(chargeState) {
        console.log("Current charge level: " + chargeState.battery_level + '%');
    });

});

**Comment by mseminatore** [comment]
Your code as written above won't work because the `vehicleDataAsync()` call happens before the `vehiclesAsync()` call completes.  In the completion of the vehicles call the options object is updated with the vehicleID which is needed in the subsequent calls. 

So you would need to next your subsequent calls within the `.done()` clauses to have an appropriate async calling flow.  The samples provide examples of the calling patterns.  All calls after vehicles can be done in parallel if you'd like.

tjs.vehiclesAsync(options).done(function(vehicle) {
   tjs.vehicleDataAsync(options).done() {
      tjs.chargeStateAsync(options).done() {
      });
   });
});
