### ISSUE TITLE
Help wanted: How to read & calculate power & energy used

### ISSUE THREAD

**Issue by h32axc** [mseminatore/TeslaJS#98]
Hi, I'm a new Model 3 owner, and have been using TeslaJS successfully to gather data on the driving state & charging state of my vehicle. I'm interested in gathering energy in vs. energy out on a per-trip and per-day basis, to calculate efficiency, etc.

Charging power (kW) & energy (kWH) are pretty obvious, e.g. latter is charge_state.charge_energy_added

But for power & energy _consumed_, all I see in the data JSON is drive_state.power.  It appears to be an instantaneous kW value, and I'm puzzled how to use it to calculate energy used in a trip (which will obviously be less than energy added in charging, due to < 100% efficiency).

Do I need to use the streaming API, so I get 250ms samples of the drive_state.power value, and sum them over the duration of the trip, then scale accordingly, to convert total kWseconds to kWH?  (Unfortunately, I have not yet successfully used the streaming API, apparently due to the known issue [here](https://github.com/mseminatore/TeslaJS/issues/93) )

Or is there a simpler way?

**Comment by mseminatore** [comment]
Hi there!  Glad to hear that your are successfully using Teslajs.  Unfortunately the Tesla API's don't provide all of the information needed for your goals.  

However, there are potentially a few work-arounds.  By looking at the power added at last charge (charge_state.**charge_energy_added**) you can estimate the power consumed in the previous day.

As you point out the charge added will be less than the electricity consumed due to efficiency losses.  But you can estimate the efficiency and correct for that.  I've seen some figures from people who have measured the power at their panel vs. what the car reports.
